const contactData = [
  {
    id: "1",
    title: "Graphics Designer",
    name: "Jhon Smith",
    social_media: "Twitter, Inc",
    address: "San Farncisco, CA 94107",
    gps_coordicates: "795 Folsom Ave, Suite 600",
    phone: "(123) 456-7890",
  },
  {
    id: "2",
    title: "CEO",
    name: "Alex Johnatan",
    social_media: "Twitter, Inc",
    address: "San Farncisco, CA 94107",
    gps_coordicates: "795 Folsom Ave, Suite 600",
    phone: "(123) 456-7890",
  },
  {
    id: "3",
    title: "Marketing Manager",
    name: "Monica Smith",
    social_media: "Twitter, Inc",
    address: "San Farncisco, CA 94107",
    gps_coordicates: "795 Folsom Ave, Suite 600",
    phone: "(123) 456-7890",
  },
  {
    id: "4",
    title: "Sales Manager",
    name: "Michael Zimber",
    social_media: "Twitter, Inc",
    address: "San Farncisco, CA 94107",
    gps_coordicates: "795 Folsom Ave, Suite 600",
    phone: "(123) 456-7890",
  },
  {
    id: "5",
    title: "Graphics Designer",
    name: "Sandra Smith",
    social_media: "Twitter, Inc",
    address: "San Farncisco, CA 94107",
    gps_coordicates: "795 Folsom Ave, Suite 600",
    phone: "(123) 456-7890",
  },
  {
    id: "6",
    title: "Graphics Designer",
    name: "Janet Carton",
    social_media: "Twitter, Inc",
    adaddress: "San Farncisco, CA 94107",
    gps_coordicates: "795 Folsom Ave, Suite 600",
    phone: "(123) 456-7890",
  },
];
